trigger:
- none

pool: rahul_test_agent_pool

stages:
  - stage: plan
    jobs:
      - job: 
        displayName: JOb1
        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: 'Rahul_service_connection'
            backendAzureRmStorageAccountName: 'stgactrahul01'
            backendAzureRmContainerName: 'rahultestcontainer'
            backendAzureRmKey: 'rahul.tfstate'
      - job:
        dependsOn: JOb1
        displayName: JOb2
        steps:
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'plan'
            environmentServiceNameAzureRM: 'Rahul_service_connection'
            backendServiceArm: 'Rahul_service_connection'
            backendAzureRmStorageAccountName: 'stgactrahul01'
            backendAzureRmContainerName: 'rahultestcontainer'
            backendAzureRmKey: 'rahul.tfstate'
